### ISSUE TITLE
Responsive UI request

### ISSUE THREAD

**Issue by iamtejasmane** [rohanjadhav05/url-shortner#1]
Hello, I have try opening this URL on my mobile phone and observed the UI components are scattered. can you make this responsive? 
Attaching the screenshot here. Thank you.

![image](https://github.com/rohanjadhav05/url-shortner/assets/99156643/a1ac138d-f189-4674-9491-b19764e4cb70)

**Comment by rohanjadhav05** [comment]
Hello Tejas,

I hope you are doing well, the issue which you were facing have
been resolved can you please check and let me know if there is anything
need to improve more

Thanks and Regards
Rohan Jadhav
